# Generated by Django 6.0.4 on 2026-04-22 09:14

import django.db.models.deletion
import ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_by', models.CharField(blank=True, max_length=320, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.CharField(blank=True, db_index=True, max_length=320, null=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=320)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='GraphSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('resource', models.CharField(db_index=True, default='', max_length=512)),
                ('change_type', models.CharField(default='', max_length=128)),
                ('notification_url', models.CharField(default='', max_length=1024)),
                ('lifecycle_notification_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('client_state', models.CharField(blank=True, max_length=256, null=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(db_index=True, max_length=256)),
                ('slot_id', models.CharField(db_index=True, max_length=128)),
                ('scenario_id', models.CharField(db_index=True, max_length=128)),
                ('execution_id', models.CharField(db_index=True, max_length=128, null=True)),
                ('executed_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('step', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'execution_history',
                'indexes': [ops.models._LongIndex(fields=['scenario_id', 'executed_at'], name='ix_execution_history_scenario_executed_at')],
                'constraints': [models.UniqueConstraint(fields=('execution_id', 'slot_id', 'scenario_id'), name='uq_execution_history_identity')],
            },
        ),
        migrations.CreateModel(
            name='GraphNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(db_index=True, max_length=128)),
                ('change_type', models.CharField(db_index=True, max_length=128)),
                ('resource', models.CharField(default='', max_length=1024)),
                ('tenant_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_state', models.CharField(blank=True, max_length=256, null=True)),
                ('lifecycle_event', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'graph_notifications',
                'constraints': [models.UniqueConstraint(fields=('subscription_id', 'resource', 'change_type', 'lifecycle_event'), name='uq_graph_notification_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=320)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('request_fingerprint', models.CharField(max_length=128)),
                ('status_code', models.IntegerField(default=200)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_keys',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'key'), name='uq_idempotency_user_key')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=320)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('dry_run', models.BooleanField(default=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='ix_jobs_status_updated_at')],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('step', models.CharField(blank=True, max_length=128, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ops.job', to_field='job_id')),
            ],
            options={
                'db_table': 'job_events',
                'indexes': [models.Index(fields=['job', 'created_at'], name='ix_job_events_job_created_at')],
            },
        ),
    ]
