# Generated by Django 6.0.4 on 2026-04-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('owner_user_id', models.CharField(db_index=True, max_length=320)),
                ('description', models.TextField(blank=True, default='')),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenarios',
            },
        ),
        migrations.CreateModel(
            name='ScenarioShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=320)),
                ('scenario', models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='catalog.scenario', to_field='scenario_id')),
            ],
            options={
                'db_table': 'scenario_shares',
                'constraints': [models.UniqueConstraint(fields=('scenario', 'user_id'), name='uq_scenario_share_user')],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('days', models.JSONField(blank=True, default=list)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalog.scenario', to_field='scenario_id')),
            ],
            options={
                'db_table': 'slots',
                'indexes': [models.Index(fields=['scenario', 'enabled'], name='ix_slots_scenario_enabled')],
            },
        ),
    ]
