# Generated by Django 6.0.4 on 2026-07-01 17:53

from django.db import migrations, models


def seed_from_scenarios_file(apps, schema_editor):  # pragma: no cover
    """Best-effort seed of the singleton from the existing ``config/scenarios.json``.

    The ``data`` block was never in the DB before — it lived only in the JSON
    file. On first deploy we lift it into the model so the in-place tokens are
    not lost. When the file is absent/unreadable (fresh install, CI), we create
    an empty singleton instead.
    """
    CatalogConfig = apps.get_model("catalog", "CatalogConfig")
    pushovers, networks, default_pushover, default_network = {}, {}, "", ""
    try:
        import json

        from app.config import load_config

        path = load_config().runtime.scenarios_file
        if path.exists():
            document = json.loads(path.read_text(encoding="utf-8"))
            data = document.get("data") or {}
            pushovers = data.get("pushovers") or {}
            networks = data.get("networks") or {}
            default_pushover = data.get("default_pushover") or ""
            default_network = data.get("default_network") or ""
    except Exception:
        # Never fail the migration on a missing/broken config file.
        pass
    CatalogConfig.objects.update_or_create(
        pk=1,
        defaults={
            "pushovers": pushovers,
            "networks": networks,
            "default_pushover": default_pushover,
            "default_network": default_network,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_owner_fk_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushovers', models.JSONField(blank=True, default=dict)),
                ('networks', models.JSONField(blank=True, default=dict)),
                ('default_pushover', models.CharField(blank=True, default='', max_length=128)),
                ('default_network', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_config',
            },
        ),
        migrations.RunPython(seed_from_scenarios_file, migrations.RunPython.noop),
    ]
